### ISSUE TITLE
Filtro data

### ISSUE THREAD

**Issue by pezzabros** [calibro/ische#2]
Dubbi sul funzionamento del filtro date

![image](https://user-images.githubusercontent.com/161997/114555830-5fa34700-9c68-11eb-8020-8750a6a7adde.png)

1. E' necessario separare il mese e l'anno? E' un po' strano perche cambiando il mese, non succerebbe niente al filtro finchè non si cambia anche l'anno.

Potremmo immaginare qualcosa come in [questo esempio](https://codesandbox.io/s/64112889month-and-year-picker-in-materialui-react-js-umsgr?file=/demo.tsx), con un month/year picker nello stesso input?

**Comment by giorgiouboldi** [comment]
Bello l'esempio! Direi si di si
